### ISSUE TITLE
code-copy doesn't work if inside code-tabs

### ISSUE THREAD

**Issue by Matsuuu** [bennypowers/rocket-presets#5]
e.g. on https://rocket.modern-web.dev/guides/first-pages/getting-started/

If you copy the highest code block, it gets copied correctly, but the ones with tabs only copy a empty string due to the textcontent not being populated

**Comment by bennypowers** [comment]
good catch! this is probably related to the a11y work i did recently. going to investigate now

**Comment by bennypowers** [comment]
fixed by 266be62a4f35ae45e146868608c3b2d3b81ca5e1 and released in [0.2.5](https://www.npmjs.com/package/rocket-preset-code-tabs/v/0.2.5)
